services:
  database:
    build: ./database/
    ports:
      - '5555:3306'
    environment:
      MARIADB_ROOT_PASSWORD: abc123
      MARIADB_DATABASE: abc
  backend:
    build: ./backend/
    ports:
      - '8080:8080'
    volumes:
      - ./backend/src/:/backend/src/
  frontend:
    build: ./frontend/
    ports: 
      - '8000:5173'
    volumes:
      - ./frontend/code/:/frontend/code/